name: Github Workflow With Docker
on: [workflow_dispatch]
jobs:
  run-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Hello World
        run: echo "Hello World"
      
