name: Github Workflow With Docker
on: [workflow_dispatch]
jobs:
  run-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
    steps:
      - name: Check out
        run: actions/checkout@v3
      
